import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    hello: "Hello, Citizen.",
    tagline: "Help us build a better nation by reporting unfinished projects securely.",
    pending_reports: "Pending Reports",
    no_pending: "No pending reports",
    upload_securely: "Upload Securely",
    privacy_first: "Privacy First",
    privacy_desc: "All photos are stripped of metadata. You can blur faces before saving.",
    new_report: "New Report",
    cancel: "Cancel",
    save: "Save",
    take_evidence: "Take Evidence Photo",
    take_evidence_desc: "Capture the unfinished infrastructure. Ensure good lighting.",
    open_camera: "Open Camera",
    blur_tooltip: "Tap or drag to blur details",
    retake: "Retake Photo",
    syncing_evidence: "Syncing Evidence",
    status_connecting: "Establishing secure connection...",
    status_encrypting: "Encrypting packets...",
    status_uploading: "Uploading to secure node...",
    status_verifying: "Verifying integrity...",
    status_success: "Evidence successfully uploaded.",
    confirm_delete: "Delete this report?",
    confirm_discard: "Discard this report?",
    sentiment_label: "Additional Details (Optional)",
    sentiment_placeholder: "Describe what you see or how you feel about this...",
    transparency_title: "Flood Control Tracker",
    transparency_desc: "Monitor government projects",
    total_projects: "Total Projects",
    total_contract_cost: "Total Contract Cost",
    unique_contractors: "Unique Contractors",
    visual: "Visual",
    table: "Table",
    cost_by_region: "Cost Distribution by Region",
    projects_by_contractor: "Projects by Contractor",
    project_desc: "Project Description",
    location: "Location",
    contractor: "Contractor",
    cost: "Cost (PHP)",
    date: "Date",
    my_profile: "My Profile",
    redirect_login: "Redirecting to login...",
    go_to_login: "Go to Login",
    reputation_score: "Reputation Score",
    credibility_points: "Credibility Points",
    my_report_history: "My Report History",
    verified_citizen_badge: "Verified Citizen Badge",
    logout: "Logout",
    loading_your_reports: "Loading your reports...",
    no_reports_submitted: "You haven't submitted any reports yet.",
    delete: "Delete",
    deleting: "Deleting...",
    unknown: "Unknown",
    unable_load_feed: "Unable to load feed",
    loading_feed: "Loading SubaybayPH...",
    no_reports_found: "No reports found yet. Be the first to report!",
    comments: "Comments",
    share: "Share",
    no_comments: "No comments yet.",
    write_comment: "Write a comment",
    post: "Post",
    close: "Close",
    anonymous: "Anonymous",
    unknown_location: "Unknown Location",
    community_report: "Community Report",
    confirm_delete_permanent: "Are you sure you want to permanently delete this report? This action cannot be undone.",
    submit_report: "Submit a Report",
    top_reports: "Top Reports",
    view_community: "View Community",
    loading: "Loading...",
    no_reports_yet: "No reports yet.",
    online: "Online",
    login: "Login",
    sign_up: "Sign Up",
    contractors_nav: "Contractors",
    map_nav: "Map",
    community_nav: "Community",
    please_login_comment: "Please login to comment."
  },
  tl: {
    hello: "Kumusta, Kababayan.",
    tagline: "Tulungan kaming bumuo ng mas mabuting bansa sa pamamagitan ng ligtas na pag-uulat ng mga hindi tapos na proyekto.",
    pending_reports: "Mga Nakabinbing Ulat",
    no_pending: "Walang nakabinbing ulat",
    upload_securely: "I-upload nang Ligtas",
    privacy_first: "Pagkapribado Una",
    privacy_desc: "Ang lahat ng larawan ay tinatanggalan ng metadata. Maaari mong labuin ang mga mukha bago i-save.",
    new_report: "Bagong Ulat",
    cancel: "Kanselahin",
    save: "I-save",
    take_evidence: "Kumuha ng Litrato",
    take_evidence_desc: "Kunan ang hindi tapos na imprastraktura. Siguraduhing maliwanag.",
    open_camera: "Buksan ang Kamera",
    blur_tooltip: "Pindutin o i-drag upang labuin",
    retake: "Kunan Ulit",
    syncing_evidence: "Nagsi-sync ng Ebidensya",
    status_connecting: "Nagtatatag ng ligtas na koneksyon...",
    status_encrypting: "Ina-encrypt ang mga packet...",
    status_uploading: "Ina-upload sa secure node...",
    status_verifying: "Bina-verify ang integridad...",
    status_success: "Matagumpay na na-upload ang ebidensya.",
    confirm_delete: "Burahin ang ulat na ito?",
    confirm_discard: "Itapon ang ulat na ito?",
    sentiment_label: "Karagdagang Detalye (Opsyonal)",
    sentiment_placeholder: "Ilarawan ang iyong nakikita o ang iyong nararamdaman tungkol dito...",
    transparency_title: "Flood Control Tracker",
    transparency_desc: "Bantayan ang mga proyekto ng gobyerno",
    total_projects: "Kabuuang Proyekto",
    total_contract_cost: "Kabuuang Halaga ng Kontrata",
    unique_contractors: "Mga Natatanging Kontratista",
    visual: "Biswal",
    table: "Talahanayan",
    cost_by_region: "Pamamahagi ng Gastos bawat Rehiyon",
    projects_by_contractor: "Mga Proyekto bawat Kontratista",
    project_desc: "Paglalarawan ng Proyekto",
    location: "Lokasyon",
    contractor: "Kontratista",
    cost: "Halaga (PHP)",
    date: "Petsa",
    my_profile: "Aking Profile",
    redirect_login: "Nagre-redirect sa pag-login...",
    go_to_login: "Pumunta sa Login",
    reputation_score: "Reputation Score",
    credibility_points: "Credibility Points",
    my_report_history: "Aking Kasaysayan ng Ulat",
    verified_citizen_badge: "Verified Citizen Badge",
    logout: "Logout",
    loading_your_reports: "Lumalabas ang iyong mga ulat...",
    no_reports_submitted: "Wala ka pang naisumiteng ulat.",
    delete: "Burahin",
    deleting: "Binubura...",
    unknown: "Hindi Alam",
    unable_load_feed: "Hindi ma-load ang feed",
    loading_feed: "Naglo-load ang SubaybayPH...",
    no_reports_found: "Wala pang mga ulat. Maging una sa pag-uulat!",
    comments: "Mga Komento",
    share: "Ibahagi",
    no_comments: "Wala pang komento.",
    write_comment: "Sumulat ng komento",
    post: "I-post",
    close: "Isara",
    anonymous: "Hindi Pinangalangan",
    unknown_location: "Hindi Alam na Lokasyon",
    community_report: "Ulat ng Komunidad",
    confirm_delete_permanent: "Sigurado ka bang permanenteng buburahin ang ulat na ito? Hindi na ito mababawi.",
    submit_report: "Mag-submit ng Ulat",
    top_reports: "Nangungunang mga Ulat",
    view_community: "Tingnan ang Komunidad",
    loading: "Naglo-load...",
    no_reports_yet: "Wala pang mga ulat.",
    online: "Online",
    login: "Login",
    sign_up: "Sign Up",
    contractors_nav: "Mga Kontratista",
    map_nav: "Mapa",
    community_nav: "Komunidad",
    please_login_comment: "Mag-login upang mag-komento."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('tl');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'tl' ? 'en' : 'tl');
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
